name: BayesianRidge
import_module: sklearn.linear_model
params:
    tol: 0.001
    alpha_1: 0.000001 
    alpha_2: 0.000001
    lambda_1: 0.000001
    lambda_2: 0.000001
    n_iter: 1000
    fit_intercept: True