name: XGBRegressor
import_module: xgboost
params:
    colsample_bynode: 0.8
    learning_rate: 1
    max_depth: 5
    num_parallel_tree: 100
    objective: 'reg:squarederror'
    subsample: 0.8
    tree_method: 'gpu_hist'