name: XGBRegressor
import_module: xgboost
params:
    booster: "gbtree"
    eta: 0.3
    gamma: 0
    max_depth: 6
    min_child_weight: 1
    max_delta_step: 0
    lambda: 0.5
    alpha: 0.5
    subsample: 0.5
    