# A test that sweeps over parameters for a Random Forest regression model.
defaults:
    - dataset: dataset_cluster
    - model: random_forest
    - override hydra/sweeper: optuna
    - override hydra/sweeper/sampler: tpe

hydra:
  mode: MULTIRUN
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: optuna_rf
    storage: null
    n_trials: 10
    n_jobs: -1
    params:
      model.params.learning_rate: 1
      model.params.colsample_bynode: interval(0.1, 0.9)
      model.params.max_depth: interval(1, 10)
      model.params.subsample: interval(0.1, 0.9)