# A test that sweeps over the alpha parameter for a ridge regression model.
defaults:
    - dataset: dataset_cluster
    - model: lasso
    - override hydra/sweeper: optuna
    - override hydra/sweeper/sampler: tpe

hydra:
  mode: MULTIRUN
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: optuna_lasso
    storage: null
    n_trials: 10
    n_jobs: -1
    params:
      model.params.alpha: interval(0, 10)