# A test that sweeps over the alpha parameter for a ridge regression model.
experiment_name: optuna_test_local

defaults:
    - dataset: loco_clean
    - model: linear
    - override hydra/sweeper: optuna
    - override hydra/sweeper/sampler: tpe

hydra:
  mode: MULTIRUN
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: ${experiment_name}
    storage: null
    n_trials: 5
    n_jobs: 1
    params:
      model.params.alpha: interval(0, 5)