# A test that sweeps over the alpha parameter for a ridge regression model.
defaults:
    - dataset: loco_clean
    - model: xgboost

hydra:
  mode: MULTIRUN
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: optuna_test
    storage: null
    n_trials: 20
    n_jobs: 1
    params:
      model.params.alpha: interval(0, 5)