# A test that sweeps over parameters for a ElasticNet regression model.
defaults:
    - dataset: dataset_cluster
    - model: elastic_net
    - override hydra/sweeper: optuna
    - override hydra/sweeper/sampler: tpe

hydra:
  mode: MULTIRUN
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: optuna_elastic
    storage: null
    n_trials: 10
    n_jobs: -1
    params:
      model.params.alpha: interval(0, 10)
      model.params.l1_ratio: interval(0, 1)