# Run a multi task elastic_net experiment that includes unknowns in the genotype matrix

experiment_name: unknowns_ld_0.2_multi_elastic

defaults:
    - dataset: dataset_unknowns_ld_0.2
    - model: multi_task_elastic