params:
    geno_bed: /scratch/capstone/ratgenes_pruned/ratgenes_pruned_0.8.bed
    geno_bim: /scratch/capstone/ratgenes_pruned/ratgenes_pruned_0.8.bim
    geno_fam: /scratch/capstone/ratgenes_pruned/ratgenes_pruned_0.8.fam
    phenotypes: /scratch/capstone/phenotypes/mass.txt
    select_traits: ''
    filter_unknowns: True
gwas_p_value: 1