params:
    geno_bed: /scratch/capstone/ratgenes_pruned/ratgenes_pruned_0.95.bed
    geno_bim: /scratch/capstone/ratgenes_pruned/ratgenes_pruned_0.95.bim
    geno_fam: /scratch/capstone/ratgenes_pruned/ratgenes_pruned_0.95.fam
    phenotypes: /scratch/capstone/phenotypes/mass.txt
    select_traits: ''
    filter_unknowns: False
gwas_p_value: 0.0
save_to_file: /scratch/capstone/mass_ld_0.95_unknowns.pkl