params:
    geno_bed: /scratch/capstone/ratgenes_pruned/ratgenes_pruned_0.95.bed
    geno_bim: /scratch/capstone/ratgenes_pruned/ratgenes_pruned_0.95.bim
    geno_fam: /scratch/capstone/ratgenes_pruned/ratgenes_pruned_0.95.fam
    phenotypes: /scratch/capstone/phenotypes/pheno_chunk1.txt
    select_traits: ''
gwas_p_value: 1