params:
    geno_bed: /scratch/capstone/ratgenes_pruned/ratgenes_pruned_0.05.bed
    geno_bim: /scratch/capstone/ratgenes_pruned/ratgenes_pruned_0.05.bim
    geno_fam: /scratch/capstone/ratgenes_pruned/ratgenes_pruned_0.05.fam
    phenotypes: /scratch/capstone/phenotypes/mass.txt
    select_traits: ''
    filter_unknowns: False
gwas_p_value: 1