params:
    geno_bed: ratgenes_pruned/ratgenes_pruned_0.8.bed
    geno_bim: ratgenes_pruned/ratgenes_pruned_0.8.bim
    geno_fam: ratgenes_pruned/ratgenes_pruned_0.8.fam
    phenotypes: phenotypes/pheno_loco_clean.txt
    select_traits:
      - 'loco_maxcent'
      - 'loco_maxdis'
      - 'loco_maxrear'
      - 'loco_maxact'
gwas_p_value: 0.05
dimensionality_reduction:
    name: PCA
    import_module: sklearn.decomposition
    params: 
        n_components: 100
        svd_solver: randomized

